FROM mcr.microsoft.com/playwright/python:v1.45.0-jammy
WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY *.py ./
CMD ["python", "-u", "ingest.py"]
