"""Baseline Academic Assessment Report generator (Engineering Studio v4).

Generates a Markdown report grounded entirely in real, computed numbers:
IndependentAuditor.audit_historical_log, measure_directive_backlog,
measure_storage_delta, and real subprocess/filesystem counts (git commits,
Python file count). No number in the generated report is hand-typed.
"""

from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Union

from .independent_auditor import IndependentAuditor
from .resource_economics import measure_directive_backlog, measure_storage_delta

PathLike = Union[str, Path]

EXECUTION_LOG_RELPATH = ".nexus_execution_log.jsonl"
DIRECTIVES_RELPATH = ".directives-ingestion"
SYSTEMS_RELPATH = "systems"
AUDIT_SAMPLE_SIZE = 1000


def _utc_iso_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _count_git_commits(repo_path: Path) -> int:
    result = subprocess.run(
        ["git", "rev-list", "--count", "HEAD"],
        cwd=str(repo_path),
        capture_output=True,
        text=True,
    )
    return int(result.stdout.strip())


def _count_python_files(engineering_studio_path: Path) -> int:
    return len(list(engineering_studio_path.rglob("*.py")))


def _mb(size_bytes: int) -> float:
    return round(size_bytes / (1024 * 1024), 2)


def generate_baseline_report(repo_path: PathLike, output_path: PathLike) -> dict:
    """Generate the Engineering Studio baseline academic assessment report.

    Runs real measurements (log audit, directive backlog, storage sizes,
    git commit count, Python file count), writes a Markdown report to
    `output_path`, and returns a dict of all raw numbers gathered.
    """
    repo = Path(repo_path).resolve()
    out_path = Path(output_path)
    if not out_path.is_absolute():
        out_path = repo / out_path

    log_path = repo / EXECUTION_LOG_RELPATH
    directives_path = repo / DIRECTIVES_RELPATH
    systems_path = repo / SYSTEMS_RELPATH
    eng_studio_path = repo / "systems" / "engineering_studio"

    auditor = IndependentAuditor()

    # 1. Audit the historical execution log for fabrication signatures.
    execution_log_audit = auditor.audit_historical_log(
        log_path=log_path, sample_size=AUDIT_SAMPLE_SIZE
    )

    # 2. Measure the real directives ingestion backlog.
    directive_backlog = measure_directive_backlog(directives_path)

    # 3. Measure real current storage sizes.
    log_storage = measure_storage_delta(log_path)
    systems_storage = measure_storage_delta(systems_path)
    storage_sizes = {
        "execution_log": log_storage,
        "systems_dir": systems_storage,
    }

    # 4. Real git commit count and real Python file count.
    commit_count = _count_git_commits(repo)
    python_file_count = _count_python_files(eng_studio_path)

    completed = directive_backlog["subdirs"].get("completed", {"file_count": 0, "total_bytes": 0})
    verdict = execution_log_audit["verdict"]
    constant_count = execution_log_audit["directives_with_constant_code_lines"]
    unique_directives = execution_log_audit["unique_directives"]
    entries_analyzed = execution_log_audit["entries_analyzed"]

    log_lines = None
    try:
        with open(log_path, "r") as f:
            log_lines = sum(1 for _ in f)
    except OSError:
        log_lines = None

    generated_at = _utc_iso_now()

    lines: list[str] = []
    lines.append("# Engineering Studio — Baseline Academic Assessment Report")
    lines.append("")
    lines.append(f"Generated: {generated_at}")
    lines.append(f"Repository: `{repo}`")
    lines.append("")
    lines.append(
        "This report is generated by "
        "`observatory.baseline_assessment.generate_baseline_report`. Every "
        "number below is the direct output of a real function call or "
        "subprocess invocation against this repository at generation time — "
        "none is hand-typed. See Methodology for exact provenance."
    )
    lines.append("")

    lines.append("## Evidence vs Architecture")
    lines.append("")
    lines.append(
        "| Claim / Architecture Property | Prior Manual Finding | "
        "Evidence (this report) |"
    )
    lines.append("|---|---|---|")
    lines.append(
        "| Metrics credibility (execution log) | Suspected fabricated "
        "(constant `code_lines` per directive) | verdict=`{verdict}`, "
        "{unique} unique directives, {const} constant-code-lines directives "
        "out of {considered} considered ({entries} entries analyzed, "
        "sample_size={sample}) |".format(
            verdict=verdict,
            unique=unique_directives,
            const=constant_count,
            considered=execution_log_audit["directives_with_constant_code_lines"]
            + execution_log_audit["directives_with_variable_code_lines"],
            entries=entries_analyzed,
            sample=AUDIT_SAMPLE_SIZE,
        )
    )
    lines.append(
        "| Storage architecture (execution log growth) | ~446MB, "
        "2,766,535 lines (prior manual count) | {mb} MB on disk right now"
        "{line_note} (`measure_storage_delta`) |".format(
            mb=_mb(log_storage["size_bytes"]),
            line_note=f", {log_lines:,} lines (recount)" if log_lines is not None else "",
        )
    )
    lines.append(
        "| Directive backlog (`completed/`) | ~67,317 files, ~38.8MB (prior "
        "manual count) | {count:,} files, {mb} MB (`measure_directive_backlog`) |".format(
            count=completed["file_count"],
            mb=_mb(completed["total_bytes"]),
        )
    )
    lines.append(
        "| Codebase size (`systems/`) | Not previously measured | {mb} MB "
        "on disk (`measure_storage_delta`) |".format(mb=_mb(systems_storage["size_bytes"]))
    )
    lines.append(
        "| Development activity (git history) | Not previously measured | "
        "{count:,} commits on HEAD (`git rev-list --count HEAD`) |".format(
            count=commit_count
        )
    )
    lines.append(
        "| Engineering Studio Python surface area | Not previously measured "
        "| {count:,} `.py` files under `systems/engineering_studio/` "
        "(`Path.rglob('*.py')`) |".format(count=python_file_count)
    )
    lines.append("")

    lines.append("## Methodology")
    lines.append("")
    full_line_note = f"{log_lines:,} lines" if log_lines is not None else "unknown line count"
    lines.append(
        "- **Execution log audit**: `IndependentAuditor.audit_historical_log("
        f"log_path='{EXECUTION_LOG_RELPATH}', sample_size={AUDIT_SAMPLE_SIZE})`. "
        "Reads the first `sample_size` lines of the JSONL log, groups "
        "`code_lines` values by `directive`, and flags directives whose "
        "`code_lines` is constant across >=5 samples as evidence of "
        "fabricated (not genuinely measured) reporting. A sample of "
        f"{AUDIT_SAMPLE_SIZE} (not the full log, which is {full_line_note}) "
        "was used because the full log is very large; the sample size "
        "is fixed and documented here so a third party can rerun the exact "
        "same call and expect the same verdict on an unchanged log."
    )
    lines.append(
        "- **Directive backlog**: `measure_directive_backlog("
        f"'{DIRECTIVES_RELPATH}')`. Real `os.scandir`/`os.stat` walk over "
        "the `pending/approved/in-progress/completed/rejected` subdirectories."
    )
    lines.append(
        "- **Storage sizes**: `measure_storage_delta('{log}')` and "
        "`measure_storage_delta('{systems}')`. Real `os.stat` (file) / "
        "`os.walk` + `os.path.getsize` (directory) calls, executed at "
        "report-generation time.".format(log=EXECUTION_LOG_RELPATH, systems=SYSTEMS_RELPATH)
    )
    lines.append(
        "- **Commit count**: `git rev-list --count HEAD` via `subprocess.run`, "
        "executed with `cwd` set to the repository root."
    )
    lines.append(
        "- **Python file count**: `Path('systems/engineering_studio').rglob('*.py')`, "
        "real filesystem walk, counted at report-generation time."
    )
    lines.append(
        "- **Execution log line count**: real line count via `open(...)` + "
        "generator sum over the log file, executed at report-generation time."
    )
    lines.append("")

    lines.append("## Limitations")
    lines.append("")
    lines.append(
        "- This report audits the execution log's *internal consistency* "
        "(whether reported metrics vary in ways consistent with genuine "
        "per-directive measurement). It does NOT verify that the underlying "
        "claimed engineering work has independent business or technical "
        "value, nor that any given directive's described change actually "
        "happened as described."
    )
    lines.append(
        f"- The execution log audit uses a sample of {AUDIT_SAMPLE_SIZE} "
        "lines (from the start of the file), not the full file, for "
        "performance reasons; this is stated explicitly so the verdict's "
        "scope is clear. A different sample size or sampling strategy "
        "could in principle produce a different verdict."
    )
    lines.append(
        "- Storage and file-count measurements are point-in-time snapshots "
        "taken at report generation and will drift as the repository "
        "continues to change."
    )
    lines.append(
        "- Directive backlog counts only files present under "
        f"`{DIRECTIVES_RELPATH}`'s five known subdirectories; files outside "
        "that structure are not counted."
    )
    lines.append(
        "- This report does not evaluate code quality, test coverage, or "
        "correctness of `systems/engineering_studio/` — only its raw size "
        "and commit-history activity."
    )
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")

    return {
        "directive_backlog": directive_backlog,
        "execution_log_audit": execution_log_audit,
        "storage_sizes": storage_sizes,
        "commit_count": commit_count,
        "python_file_count": python_file_count,
        "execution_log_line_count": log_lines,
        "generated_at": generated_at,
        "output_path": str(out_path),
    }
